export const DEPARTMENT_REQUEST_REQUEST = "DEPARTMENT_REQUEST_REQUEST"
export const DEPARTMENT_REQUEST_SUCCESS = "DEPARTMENT_REQUEST_SUCCESS"
export const DEPARTMENT_REQUEST_FAILURE = "DEPARTMENT_REQUEST_FAILURE"

export const DEPARTMENT_REQUEST_RECORDS_REQUEST = "DEPARTMENT_REQUEST_RECORDS_REQUEST"
export const DEPARTMENT_REQUEST_RECORDS_SUCCESS = "DEPARTMENT_REQUEST_RECORDS_SUCCESS"
export const DEPARTMENT_REQUEST_RECORDS_FAILURE = "DEPARTMENT_REQUEST_RECORDS_FAILURE"