export const ALL_SUPPLIERS_LIST_REQUEST = "ALL_SUPPLIERS_LIST_REQUEST"
export const ALL_SUPPLIERS_LIST_SUCCESS = "ALL_SUPPLIERS_LIST_SUCCESS"
export const ALL_SUPPLIERS_LIST_FAILURE = "ALL_SUPPLIERS_LIST_FAILURE"