export const ALL_SUPPLIERS_LIST_REQUEST = "ALL_SUPPLIERS_LIST_REQUEST"
export const ALL_SUPPLIERS_LIST_SUCCESS = "ALL_SUPPLIERS_LIST_SUCCESS"
export const ALL_SUPPLIERS_LIST_FAILURE = "ALL_SUPPLIERS_LIST_FAILURE"

export const ADD_NEW_SUPPLIER_REQUEST = "ADD_NEW_SUPPLIER_REQUEST"
export const ADD_NEW_SUPPLIER_SUCCESS = "ADD_NEW_SUPPLIER_SUCCESS"
export const ADD_NEW_SUPPLIER_FAILURE = "ADD_NEW_SUPPLIER_FAILURE"