export const INVENTORY_LIST_REQUEST = "INVENTORY_LIST_REQUEST"
export const INVENTORY_LIST_SUCCESS = "INVENTORY_LIST_SUCCESS"
export const INVENTORY_LIST_FAILURE = "INVENTORY_LIST_FAILURE"

export const SUPPLIER_TYPES_REQUEST = "SUPPLIER_TYPES_REQUEST"
export const SUPPLIER_TYPES_SUCCESS = "SUPPLIER_TYPES_SUCCESS"
export const SUPPLIER_TYPES_FAILURE = "SUPPLIER_TYPES_FAILURE" 