export const GET_OTP_REQUEST = "GET_OTP_REQUEST"
export const GET_OTP_SUCCESS = "GET_OTP_SUCCESS"
export const GET_OTP_FAILURE = "GET_OTP_FAILURE"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"